### PR TITLE
feat:  🚀 Added a feature to pass environment variables in Terraform workflows and TFDrift workflows.

### PR DESCRIPTION
**Pull request by VishwajitNagulkar**
## what
*  Added a feature to pass environment variables in Terraform workflows and TFDrift workflows.
* Resolved issues facing in tfdrift workflow

### CODE REVIEW

**Review by nileshgadgi — APPROVED** [review]
LGTM!

**Review by d4kverma — APPROVED** [review]
LGTM

**Review by themaniskshah — APPROVED** [review]

**Comment by ballalamit** [comment]
LGTM

**Review by ballalamit — APPROVED** [review]

**Comment by nileshgadgi** [comment]
Can you send screenshot of working action, where we are getting these env values. Thanks!

**Comment by VishwajitNagulkar** [comment]
> Can you send screenshot of working action, where we are getting these env values. Thanks!

Screenshot from 2023-10-05 17-25-41

I set environment variables in first step then you can see in second step there is KAFKA_API_KEY: test value assigned in env

**Pull request merged**
