### PR TITLE
feat: created shared workflow for toc

### PR DESCRIPTION
**Pull request by Tanveer143s**
## what
* created shared workflow for toc readme upgradation

## reference
* below link is for custom GitHub action for toc
* https://github.com/clouddrove/github-actions/tree/internal_502/toc

### CODE REVIEW

**Review by VishwajitNagulkar — COMMENTED** [review]
Prepare doc on it.

**Review by omsharma07 — DISMISSED** [review]
LGTM

**Review by d4kverma — DISMISSED** [review]
LGTM

**Review by anmolnagpal — DISMISSED** [review]

**Review by VishwajitNagulkar — DISMISSED** [review]
LGTM

**Review by anmolnagpal — APPROVED** [review]

**Pull request closed without merging**
